global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

#Holaaaaaaaaaaa
  - job_name: 'net-services'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets:
          - 'omnicode-api-authentication.azurewebsites.net:443'
          - 'omnicode-api-calls.azurewebsites.net:443'
          - 'omnicode-api-real-time.azurewebsites.net:443'
          - 'omnicode-api-session.azurewebsites.net:443'
          - 'omnicode-api-orchestrator.azurewebsites.net:443'